### PR TITLE
I made the service and edited the Controller

### PR DESCRIPTION
**Pull request by Artistic-King4777**
I made the service package and PersonService Class along with a note about the import for exceptions and repository and with approval from SM I edited the PersonController some and implemented loggers into the methods

### CODE REVIEW

**Review by senorcl0ud — CHANGES_REQUESTED** [review]
Great job in updating the controller class to be in the proper package. 
For the log object, could you include the actual id that you're checking for in the information getting logged?
Also instead of saying "GOT" why not just say "GET" to match the RequestMethod?

**Review by Jermaine34343 — COMMENTED** [review]
Do exactly what claude said

**Review by Jermaine34343 — APPROVED** [review]
I like the changes

**Review by senorcl0ud — APPROVED** [review]
I would have been fine if you just said  "GET:" instead of "GETTING" but that's negligible. Good job on updating the logger too.

**Pull request merged**
