### PR TITLE
110_PersonRepository

### PR DESCRIPTION
**Pull request by zeeman0306**
created PersonRepository interface, extending CRUDRepository

### CODE REVIEW

**Review by Jermaine34343 — APPROVED** [review]

**Comment by senorcl0ud** [comment]
No package.

**Review by senorcl0ud — CHANGES_REQUESTED** [review]
Put the file in the proper package as per the ticket.

**Review by senorcl0ud — CHANGES_REQUESTED** [review]
The exceptions package shouldn't be inside of the domain pacakge.  -Domain pacakage should also be lowercase
Also the PersonController class is expected to be inside a controller pacakge

**Comment by senorcl0ud** [comment]
Only commit the files you touch. We shouldn't need anything else done to the pom at this point.
Good job so far guys, just gotta tighten up that attention to detail.

**Review by senorcl0ud — CHANGES_REQUESTED** [review]
This should not be inside the Domain package

**Pull request closed without merging**
